# Generated by Django 5.0.6 on 2024-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_post_id_post_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
